config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, skip: %i[sessions registrations]
  as :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session

    get 'sign_up', to: 'devise/registrations#new', as: :new_user_registration
    post 'sign_up', to: 'devise/registrations#create', as: :user_registration
  end

  get 'groups/:id/join', to: 'groups#join', as: :join_group
  get 'groups/:id/leave/:user_id', to: 'groups#leave', as: :leave_group
  get 'groups/:id/request', to: 'groups#request_join', as: :request_group
  get 'groups/:id/accept/:user_id', to: 'groups#accept_join', as: :accept_group
  resources :groups do
    resources :posts, except: %i[index new edit]
  end

  resources :posts, only: %i[] do
    resources :comments, only: %i[create update destroy]
  end

  root 'groups#index'
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  enum :privacy, %i[open restricted]

  belongs_to :user
  has_many :posts, dependent: :destroy

  has_many :group_enrollments, dependent: :destroy
  has_many :users, through: :group_enrollments, source: :user

  validates :title, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :privacy, presence: true

  def requests
    group_enrollments.where(joined: false).map(&:user)
  end

  def members
    group_enrollments.where(joined: true).map(&:user)
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, except: %i[index new create]
  before_action :validate_group_ownership!, only: %i[edit update destroy leave accept_join]
  before_action :validate_user_enrollment!, only: :show

  def index
    @groups = Group.all
  end

  def show
    @posts = @group.posts.all
  end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        GroupEnrollment.create(user: current_user, group: @group, joined: true)

        format.turbo_stream do
          render turbo_stream: turbo_stream.append('groups',
                                                   partial: 'groups/group',
                                                   locals: { group: @group })
        end
        format.html { redirect_to group_url(@group), notice: locale('created') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@group,
                                                    partial: 'groups/show_group',
                                                    locals: { group: @group })
        end
        format.html { redirect_to group_url(@group), notice: locale('updated') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy

    redirect_to groups_url, notice: locale('destroyed')
  end

  def join
    GroupEnrollment.create(user: current_user, group: @group, joined: true)

    redirect_to @group, notice: I18n.t('groups.join.success')
  end

  def leave
    user = User.find(params[:user_id])
    raise if current_user != @group.user || user == @group.user

    GroupEnrollment.find_by(user: user, group: @group).destroy

    redirect_to @group, notice: I18n.t('groups.leave.success')
  rescue StandardError
    redirect_to @group, notice: I18n.t('groups.leave.failed')
  end

  def request_join
    GroupEnrollment.create(user: current_user, group: @group)

    redirect_to groups_url, notice: I18n.t('groups.join.success')
  end

  def accept_join
    user = User.find(params[:user_id])
    raise if current_user != @group.user || user == @group.user

    enrrollement = GroupEnrollment.find_by(user: user, group: @group)

    params[:accepted] == 'true' ? enrrollement.update(joined: true) : enrrollement.destroy

    redirect_to @group, notice: I18n.t('groups.leave.success')
  rescue StandardError
    redirect_to @group, notice: I18n.t('groups.leave.failed')
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:title, :privacy).merge(user: current_user)
  end

  def validate_group_ownership!
    validate_ownership!(@group)
  end

  def locale(action)
    I18n.t('notice.success', action: action, resource: 'Group')
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
  def group_form_submit_name(action_name)
    action_name == 'edit' ? 'Save' : 'Create'
  end

  def group_form_title(action_name)
    action_name == 'edit' ? 'Edit' : 'Create'
  end

  def group_actions(group)
    return if current_owner?(group)

    enrollment = GroupEnrollment.find_by(user: current_user, group: group)

    return button_tag 'Joined', class: 'btn-primary' if enrollment&.joined == true
    return button_tag 'Waiting for access', class: 'btn-secondary' if enrollment&.joined == false

    if group.restricted?
      link_to 'Request join', request_group_path(group), class: 'btn-secondary'
    else
      link_to 'Join', join_group_path(group), class: 'btn-secondary'
    end
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: 'contents') do |form| %>
  <h1 class="text-3xl text-bold"><%= group_form_title(action_name) %> Group</h1>
  <div class="flex mt-5 w-full items-center">
    <div class="flex flex-col w-1/3">
      <strong class="text-bold text-lg">Group name</strong>
      <p class="text-gray-700 text-sm w-2/3">People will see this name before joining your group</p>
    </div>
    <div class="flex flex-col w-2/3 pl-20">
      <%= form.text_field :title, class: 'form-input-text', placeholder: 'My group' %>
    </div>
  </div>
  <div class="flex mt-5 w-full">
    <div class="flex flex-col w-1/3">
      <strong class="text-bold text-lg">Access control</strong>
      <p class="text-gray-700 text-sm">
        Open means anyone can join. Private means you have to accept their request. Secret means
        that you have to invite them to join.
      </p>
    </div>
    <div class="flex w-2/3 h-12 pl-20">
      <%= form.hidden_field :privacy, value: group.privacy ? group.privacy : 'open', readonly: true %>
      <% Group.privacies.each do |key, value| %>
        <%= button_tag key.capitalize, class: 'form-input-radio', remote: true, data: { controller: 'groups', action: 'groups#setPrivacyInput', groups_privacy_param: key } %>
      <% end %>
    </div>
  </div>
  <div class="flex mt-10 justify-end space-x-6 w-full">
    <%= button_tag 'Close', type: 'button', class: 'btn-secondary', data: { action: 'turbo-modal#hideModal' } %>
    <%= form.submit group_form_submit_name(action_name), class: 'btn-primary' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <div class="flex items-center justify-between mt-5 w-2/3">
    <h1 class="font-bold text-2xl">
      <%= link_to group.title, group %>
    </h1>
    <%= group_actions(group) %>
  </div>
</div>

app/views/groups/_members.html.erb
<% if current_owner?(group) %>
<div class="flex-col">
  <h1 class="title-secondary">Members</h1>
  <% group.members.each do |member| %>
    <div class="flex mt-5 items-center">
        <div class="w-2/3">
          <%= member.email %>
        </div>
        <div class="w-1/3">
          <% unless current_user == member %>
            <%= link_to leave_group_url(group, member) do %>
              <i class="fa-solid fa-x"></i>
            <% end %>
          <% end %>
        </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/groups/_requests.html.erb
<% if current_owner?(group) %>
<div class="flex-col mt-20">
  <h1 class="title-secondary">Requests</h1>
  <% group.requests.each do |user| %>
    <div class="flex mt-5 items-center">
        <div class="w-2/3">
          <%= user.email %>
        </div>
        <div class="w-1/3 space-x-2">
          <%= link_to accept_group_url(group, user, accepted: true) do %>
            <i class="fa-solid fa-check"></i>
          <% end %>
          <%= link_to accept_group_url(group, user, accepted: false) do %>
            <i class="fa-solid fa-x"></i>
          <% end %>
        </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/groups/_show_group.html.erb
<div id="<%= dom_id group %>">
  <div class="flex items-center">
    <h1 class="title-primary"><%= group.title %></h1>
    <% if can_edit_or_delete?(group) %>
      <%= button_to edit_group_url(group), method: :get, data: { turbo_frame: 'groups_form_modal' } do %>
        <i class="fa-solid fa-gear ml-10 text-3xl text-gray-700"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<%= turbo_frame_tag :groups_form_modal do %>
  <%= tag.div data: { controller: 'turbo-modal', turbo_modal_target: 'modal',
                      action: 'turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeWithClick' },
                      class: 'groups-modal' do %>
    <%= render 'form', group: @group %>
  <% end %>
<% end %>

app/views/groups/index.html.erb
<div class="flex w-full flex-col">
  <h1 class="title-primary">Groups</h1>
  <div class="flex w-full items-center">
    <div class="flex">
      <!-- Filters -->
    </div>
    <div class="flex w-full justify-end">
      <%= button_to new_group_url, method: :get, data: { turbo_frame: 'groups_form_modal' }, class: 'btn-primary' do %>
        <i class="fa-solid fa-plus"></i> Create a new group
      <% end %>
    </div>
  </div>
  <div id="groups" class="min-w-full mt-10">
    <%= render @groups %>
  </div>
</div>

app/views/groups/new.html.erb
<%= turbo_frame_tag :groups_form_modal do %>
  <%= tag.div data: { controller: 'turbo-modal', turbo_modal_target: 'modal',
                      action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeWithClick" },
                      class: 'groups-modal' do %>
    <%= render 'form', group: @group %>
  <% end %>
<% end %>

app/views/groups/show.html.erb
<div class="flex w-full space-x-20">
  <div class="flex-col w-3/4 mt-5">
    <%= render 'show_group', group: @group %>
    <div class="mt-5">
      <%= render partial: 'posts/form', locals: { post: @group.posts.build } %>
    </div>
    <div class='mt-30'>
      <h1 class="title-secondary">All posts</h1>
      <%= render partial: 'posts/post', collection: @posts %>
    </div>
  </div>
  <div class="flex-col w-1/4 mt-5">
    <%= render 'members', group: @group %>
    <%= render 'requests', group: @group %>
  </div>
</div>