config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, skip: %i[sessions registrations]
  as :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session

    get 'sign_up', to: 'devise/registrations#new', as: :new_user_registration
    post 'sign_up', to: 'devise/registrations#create', as: :user_registration
  end

  get 'groups/:id/join', to: 'groups#join', as: :join_group
  get 'groups/:id/leave/:user_id', to: 'groups#leave', as: :leave_group
  get 'groups/:id/request', to: 'groups#request_join', as: :request_group
  get 'groups/:id/accept/:user_id', to: 'groups#accept_join', as: :accept_group
  resources :groups do
    resources :posts, except: %i[index new edit]
  end

  resources :posts, only: %i[] do
    resources :comments, only: %i[create update destroy]
  end

  root 'groups#index'
end

app/views/layouts/_navbar.html.erb
<nav class="bg-white border-gray-200 px-2 py-2.5">
  <div class="container flex items-center justify-between mx-auto">
    <div class="flex">
      <% if current_user %>
        User: <%= current_user.full_name %>
      <% end %>
    </div>
    <ul class="flex space-x-6">
      <li><%= link_to 'Groups', groups_url, class: 'navbar-link' %></li>
      <% if current_user %>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'navbar-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<div class="relative bg-green-100 border-l-4 border-green-500 text-gray-700 p-4 mt-2 w-80" data-controller="alerts" data-alerts-animation-class="transition duration-500 ease-in-out transform opacity-0">
  <h1 class="font-bold"><%= content %></h1>
  <a href="<%= link %>">View comment</a>
  <span class="absolute top-0 bottom-0 right-0 px-4 py-4">
    <a href="#" data-action="click->alerts#close">
      <svg class="fill-current h-6 w-6 text-black" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
        <title>Close</title>
        <path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/>
      </svg>
    </a>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simplero Social</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-gray-100">
    <%= render 'layouts/navbar' %>
    <main class="container relative mx-auto mt-5 px-5 flex">
      <div id="notifications" class="absolute top-0 right-0 flex-col"></div>
      <%= turbo_frame_tag :groups_form_modal %>
      <%= yield %>
    </main>
  </body>
</html>